name: Deploy

on:
  push:
    branches: [ development ]
    
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker images
      run: |
        docker-compose -f ./docker-compose.yml build
        docker-compose -f ./docker-compose.yml push
